Repository IT2901-SINTEF01/backend, pull requests merged in 2021-03, with the labels that each got.

#72 Merge azure deployment into docker.yml
  .github/workflows/docker.yml
  .github/workflows/master_sintef01.yml
Labels: ci/cd

#73 Set up cors to allow requests from *.vercel.app
  Startup.cs
Labels: ci/cd

#78 Use generic class for "injecting" metadata field into GraphQL type
  Models/MetAPI/GraphQLTypes/ForecastType.cs
  utils/GraphQLTypes/ObjectGraphTypeWithMetadata.cs
Labels: enhancement

#80 Make use of IMiddleware in OptionsMiddleware
  utils/OptionsMiddleware.cs
Labels: enhancement

#97 Change string
  Models/SSB/GraphQLTypes/PopulationInNorwayType.cs
Labels: bug

#95 Change semver for graphql packages and update startup code
  Backend.csproj
  Startup.cs
Labels: enhancement

#102 Made treshold field nullable
  BackendTests/GraphQLTests/VisualisationTypeTest.cs
  Models/Base/Metadata/GraphQLTypes/VisualisationType.cs
Labels: bug

#109 Update versions (mimic dependabot)
  Backend.csproj
Labels: enhancement
