Repository IT2901-SINTEF01/backend, pull requests merged in 2021-02, with the labels that each got.

#9 Create dotnet.yml
  .github/workflows/dotnet.yml
Labels: tests

#10 Create dummy GraphQL endpoint
  API/Queries/Resolvers/SampleResolver.cs
  API/Queries/SampleQuery.cs
  API/Schemas/SampleSchema.cs
  Backend.csproj
  BackendTests/IndexResponseTest.cs
  Controllers/IndexController.cs
  IndexResponse.cs
  Properties/launchSettings.json
  Startup.cs
Labels: enhancement

#11 Implement linting with restyled and actions
  .restyled.yaml
Labels: enhancement

#27 Set up dependabot
  .github/dependabot.yml
Labels: ci/cd

#48 47 make forecast more compliant
  Mocks/MetAPI/Compact.cs
Labels: bug

#52 Tag docker images
  .github/workflows/docker.yml
Labels: ci/cd, github_actions
